# Generated by Django 5.0.7 on 2024-11-11 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='disbursement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_windows', to='account.disbursementdata'),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='input_window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_windows', to='account.inputwindow'),
        ),
        migrations.AlterField(
            model_name='settlementwindow',
            name='disbursement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settle_windows', to='account.disbursementdata'),
        ),
    ]
